### ISSUE TITLE
Unable to process file

### ISSUE THREAD

**Issue by adrianignat13** [benwatson528/intellij-avro-parquet-plugin#25]
I am trying to view files dumped by Azure Capture from Azure EventHubs to Azure BlobStorage and I get the following error:

2020-05-22 14:13:10,761 [246031109]  ERROR - ij.viewer.FileViewerToolWindow - IntelliJ IDEA 2020.1.1  Build #IC-201.7223.91 
2020-05-22 14:13:10,761 [246031109]  ERROR - ij.viewer.FileViewerToolWindow - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-05-22 14:13:10,761 [246031109]  ERROR - ij.viewer.FileViewerToolWindow - OS: Windows 10 
2020-05-22 14:13:10,761 [246031109]  ERROR - ij.viewer.FileViewerToolWindow - Plugin to blame: Avro and Parquet Viewer version: 1.1.2 
2020-05-22 14:14:04,793 [246085141]   INFO - ij.viewer.FileViewerToolWindow - Received file D:\downloads\13_02_45_29.avro 
2020-05-22 14:14:04,803 [246085151]   INFO - ewer.fileformat.AvroFileReader - Retrieved 347 records 
2020-05-22 14:14:04,842 [246085190]   INFO - ij.viewer.table.TableFormatter - Found 6 unique columns 
2020-05-22 14:14:24,678 [246105026]  ERROR - ij.viewer.FileViewerToolWindow - Unable to process file 
java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:179)
	at uk.co.hadoopathome.intellij.viewer.table.TableFormatter.getRows(TableFormatter.java:44)
	at uk.co.hadoopathome.intellij.viewer.table.JTableHandler.updateTable(JTableHandler.java:30)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:178)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:168)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by benwatson528** [comment]
Hi Adrian,

Do you have a sample file that you could share so I can recreate this error?

Ben

**Comment by adrianignat13** [comment]
The file contains sensitive information and I don't know how to obfuscate it. Weird enough, I have another, smaller file, dumped also by Azure Capture that the plugin can open.

**Comment by benwatson528** [comment]
I'm not able to recreate this issue myself, but I've built a version of the plugin that will either fix your issue or print:

```java
LOGGER.error(
    String.format("Caught JsonObject issue for row [%s], value [%s] and col [%s]",
    flattenedRecordCopy, valueCopy, colCopy));
```

If you could please install the zip version of the plugin from [here](https://github.com/benwatson528/intellij-avro-parquet-plugin/blob/Handling-Json-Objects/intellij-avro-parquet-viewer-1.1.2.zip) (Plugins -> click the cog -> Install Plugin from Disk...) and let me know what happens when you try with the broken file?

**Comment by adrianignat13** [comment]
That fixes the issue. I am impressed with the quick response and the quick fix, without a valid file to test with. Kudos to you kind sir.

**Comment by benwatson528** [comment]
Great news, thanks for confirming. I'll do an official release with the fix in this weekend.

**Comment by benwatson528** [comment]
@adrianignat13 the update is live on the marketplace now.
