### ISSUE TITLE
Unable to process file produced by parquet4s

### ISSUE THREAD

**Issue by gygabyte** [benwatson528/intellij-avro-parquet-plugin#46]
I am getting this error when processing a file that is produced by the the scala library parquet4s.
In this case it was written using snappy compression, but the same issue occurs for an uncompressed file

```
Unable to process file  <filename>.snappy.parquet

org.apache.avro.SchemaParseException: Illegal character in: parquet4s-schema
	at org.apache.avro.Schema.validateName(Schema.java:1530)
	at org.apache.avro.Schema.access$400(Schema.java:87)
	at org.apache.avro.Schema$Name.<init>(Schema.java:673)
	at org.apache.avro.Schema.createRecord(Schema.java:212)
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:270)
	at org.apache.parquet.avro.AvroSchemaConverter.convert(AvroSchemaConverter.java:248)
	at org.apache.parquet.avro.AvroReadSupport.prepareForRead(AvroReadSupport.java:130)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:183)
	at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:156)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
	at uk.co.hadoopathome.intellij.viewer.fileformat.ParquetFileReader.getRecords(ParquetFileReader.java:44)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:180)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:171)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Thanks Pedro

**Comment by benwatson528** [comment]
Hi Pedro,

Do you have a sample file?

Thanks,

Ben

**Comment by benwatson528** [comment]
Hi Pedro,

This is because I use [`org.apache.parquet.avro.AvroParquetReader`](https://www.javadoc.io/doc/org.apache.parquet/parquet-avro/1.11.0/org/apache/parquet/avro/AvroParquetReader.html) to read files, and hyphens (`-`) are invalid characters in Avro schemas.

I'm afraid that this isn't something that I can change, but replacing hyphens with underscores in your column names would resolve this.

Thanks,

Ben

**Comment by gygabyte** [comment]
Hi Ben,

the column names don't have hyphens, only underscores.


[04-45.parquet.zip](https://github.com/benwatson528/intellij-avro-parquet-plugin/files/5201168/04-45.parquet.zip)

**Comment by benwatson528** [comment]
https://github.com/mjakubowski84/parquet4s/issues/131 - if you update to parquet4s 1.1.0 then this issue will be resolved.

I hope this helps.

Ben

**Comment by benwatson528** [comment]
Not at all, happy to help. It's surprising how inconsistent and weird all of the Parquet and Avro libraries are. When I made this plugin I thought it would be 5 lines of code and I'd never have to worry about it again!
