### ISSUE TITLE
Not an Avro data file in 2021.1

### ISSUE THREAD

**Issue by mkosmowski** [benwatson528/intellij-avro-parquet-plugin#66]
I just installed the plugin in my fresh IntelliJ 2021.1 and no matter what file I'm trying to read I keep getting "Unable to process file" error accompanied by such stacktrace:

```
Unable to process file C:\Users\kosmowsm\dev\repos\gyst-tools\gyst\src\main\resources\schema\collection-schema.avro

org.apache.avro.InvalidAvroMagicException: Not an Avro data file.
	at org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:111)
	at org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:139)
	at org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:114)
	at uk.co.hadoopathome.intellij.viewer.fileformat.AvroFileReader.getRecords(AvroFileReader.java:35)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:180)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:171)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834) 
```

Sample avro file I'm trying:
```
{
  "type" : "record",
  "name" : "twitter_schema",
  "namespace" : "com.miguno.avro",
  "fields" : [ {
    "name" : "username",
    "type" : "string",
    "doc"  : "Name of the user account on Twitter.com"
  }, {
    "name" : "tweet",
    "type" : "string",
    "doc"  : "The content of the user's Twitter message"
  }, {
    "name" : "timestamp",
    "type" : "long",
    "doc"  : "Unix epoch time in seconds"
  } ],
  "doc:" : "A basic schema for storing Twitter messages"
}
```

OS/IDE version data:
IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 900M
Cores: 8

**Comment by benwatson528** [comment]
Hi,

That is an Avro schema file and not an Avro data file, and so should be given the extension `.avsc`. This plugin doesn't support `.avsc` files as they're just plain JSON and so can be viewed in the normal IntelliJ editor pane, or by a JSON-viewing plugin such as [Json Parser](https://plugins.jetbrains.com/plugin/10650-json-parser).

**Comment by mkosmowski** [comment]
Oh, that's quite a difference I wasn't aware of. Thanks for explanation!
