### ISSUE TITLE
Im facing the below error and 1 observation

### ISSUE THREAD

**Issue by Nitin-pgmr** [benwatson528/intellij-avro-parquet-plugin#80]
org.apache.avro.SchemaParseException: Illegal initial character: (o) Oceania refers to Australia/New Zealand, Melanesia, Micronesia, and Polynesia subregions.
	at org.apache.avro.Schema.validateName(Schema.java:1562)
	at org.apache.avro.Schema.access$400(Schema.java:91)
	at org.apache.avro.Schema$Field.<init>(Schema.java:546)
	at org.apache.avro.Schema$Field.<init>(Schema.java:585)
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:280)
	at org.apache.parquet.avro.AvroSchemaConverter.convert(AvroSchemaConverter.java:264)
	at org.apache.parquet.avro.AvroReadSupport.prepareForRead(AvroReadSupport.java:134)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:185)
	at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:156)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
	at uk.co.hadoopathome.intellij.viewer.fileformat.ParquetFileReader.getRecords(ParquetFileReader.java:99)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:193)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:184)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Is this a pycharm restriction
Also only 1 tab can be used at once in pycharm to view the parquet file

**Comment by benwatson528** [comment]
Hello,

The first error means the column name isn't valid - see https://avro.apache.org/docs/current/spec.html#names for column rules.

As for the bottom one, that's a limitation of Jetbrains IDEs - there's only one Tool Window per instance.

**Comment by benwatson528** [comment]
Hello,

The first error means the column name isn't valid - see https://avro.apache.org/docs/current/spec.html#names for column rules.

As for the bottom one, that's a limitation of Jetbrains IDEs - there's only one Tool Window per instance.
