### ISSUE TITLE
Unable to use on Mac M1 (Aarch64)

### ISSUE THREAD

**Issue by luketn** [benwatson528/intellij-avro-parquet-plugin#81]
Hi,
I used the plugin on my previous mac and loved it, but since switching to the M1 family of Macs I have this error:
![image](https://user-images.githubusercontent.com/1756555/140457210-7349fa4a-21b6-4309-977d-89aef7b39d97.png)

(error detail below)

Would you consider an update that supports M1, or let me know how to go about resolving this?

I did a little further research and I believe the Xerial snappy library does support M1, but maybe the plugin needs to be updated to a more recent version?
https://github.com/xerial/snappy-java/issues/279

Stack trace:
```
Unable to process file /private/var/folders/8n/5c3_bt153s94pgl3gfdwqx3r0000gn/T/1636083936286-0/weather.parquet/part-00000-f79c3105-d729-4006-9b0c-3a3c2bdcb98f-c000.snappy.parquet

org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
	at org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:361)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:195)
	at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:167)
	at org.xerial.snappy.Snappy.init(Snappy.java:69)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:46)
	at org.apache.parquet.hadoop.codec.SnappyDecompressor.decompress(SnappyDecompressor.java:62)
	at org.apache.parquet.hadoop.codec.NonBlockedDecompressorStream.read(NonBlockedDecompressorStream.java:51)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
	at org.apache.parquet.bytes.BytesInput$StreamBytesInput.toByteArray(BytesInput.java:286)
	at org.apache.parquet.bytes.BytesInput.toByteBuffer(BytesInput.java:237)
	at org.apache.parquet.column.values.dictionary.PlainValuesDictionary$PlainBinaryDictionary.<init>(PlainValuesDictionary.java:91)
	at org.apache.parquet.column.values.dictionary.PlainValuesDictionary$PlainBinaryDictionary.<init>(PlainValuesDictionary.java:74)
	at org.apache.parquet.column.Encoding$1.initDictionary(Encoding.java:90)
	at org.apache.parquet.column.Encoding$5.initDictionary(Encoding.java:163)
	at org.apache.parquet.column.impl.ColumnReaderBase.<init>(ColumnReaderBase.java:413)
	at org.apache.parquet.column.impl.ColumnReaderImpl.<init>(ColumnReaderImpl.java:46)
	at org.apache.parquet.column.impl.ColumnReadStoreImpl.getColumnReader(ColumnReadStoreImpl.java:82)
	at org.apache.parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:271)
	at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:147)
	at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:109)
	at org.apache.parquet.filter2.compat.FilterCompat$NoOpFilter.accept(FilterCompat.java:177)
	at org.apache.parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:109)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:136)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:225)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:132)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:136)
	at uk.co.hadoopathome.intellij.viewer.fileformat.ParquetFileReader.getRecords(ParquetFileReader.java:99)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:193)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:184)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by benwatson528** [comment]
Thanks for bringing it to my attention. I don't have an M1 Mac to test this on but the plugin is due a version bump across all dependencies so hopefully that fixes it. Would you be able to test it for me once I have please? I'll upload the zip here sometime this weekend and let you know.

**Comment by luketn** [comment]
Awesome, thanks! Yes I will be happy to try it. I haven’t tested a pre-release plugin before - I look forward to giving it a go!

**Comment by benwatson528** [comment]
I have updated just Snappy to see if that helps. I can't attach 60MB files to GitHub so you can download the file from my Google Drive at https://drive.google.com/file/d/1DzV7SuzRChkHAF50QRlsn4t0ttYj9xZ6/view?usp=sharing.

If you would rather build it yourself then checkout https://github.com/benwatson528/intellij-avro-parquet-plugin/tree/Updating-Xerial and follow the instructions at https://github.com/benwatson528/intellij-avro-parquet-plugin/tree/Updating-Xerial#building-locally to build it.

To install it, uninstall the plugin from the marketplace, restart your IDE and then install the zip from the plugin installation page.

**Comment by luketn** [comment]
Hi Ben! It worked!

I uninstalled the marketplace plugin, downloaded the zip from your Google Drive and installed it from disk:

![image](https://user-images.githubusercontent.com/1756555/142716112-59ea3b3a-f26e-490f-9803-1408230eb8ae.png)

**Comment by benwatson528** [comment]
Thanks Luke I'll try and get an update out this week. I'll let you know when it's on the marketplace.

**Comment by benwatson528** [comment]
Hi @luketn, the update is live on the marketplace so you can uninstall the zip and re-install from the marketplace.
