### ISSUE TITLE
Exception generated while trying to view parquet files with dash formated uuid's as the column names

### ISSUE THREAD

**Issue by neil-hucker-seequent** [benwatson528/intellij-avro-parquet-plugin#94]
Description:
When trying to view a parquet file with the plugin, if I use a file that contains uuid4 column name with dash formatting, the plugin throws the below exception and is unable to load the file.

The file was generated by PyArrow using parquet version 2.6, and zstd compression. Sample file attached.

org.apache.avro.SchemaParseException: Illegal character in: d3d3d3d3-4b40-4d1c-bed1-3a2ed76be83a
	at org.apache.avro.Schema.validateName(Schema.java:1566)
	at org.apache.avro.Schema.access$400(Schema.java:91)
	at org.apache.avro.Schema$Field.<init>(Schema.java:546)
	at org.apache.avro.Schema$Field.<init>(Schema.java:585)
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:280)
	at org.apache.parquet.avro.AvroSchemaConverter.convert(AvroSchemaConverter.java:264)
	at org.apache.parquet.avro.AvroReadSupport.prepareForRead(AvroReadSupport.java:134)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:185)
	at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:156)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
	at uk.co.hadoopathome.intellij.viewer.fileformat.ParquetFileReader.getRecords(ParquetFileReader.java:99)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:193)
	at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:184)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829
[CENPLAT-5827_64blks_ijk_zero_col_Rock_Measure_In_Bool_In.zip](https://github.com/benwatson528/intellij-avro-parquet-plugin/files/8201476/CENPLAT-5827_64blks_ijk_zero_col_Rock_Measure_In_Bool_In.zip)
)

**Comment by benwatson528** [comment]
Hello see https://github.com/benwatson528/intellij-avro-parquet-plugin/issues/68.
