### ISSUE TITLE
"IDE error occurred" after enabling the plugin in the settings

### ISSUE THREAD

**Issue by jeremie-koster** [benwatson528/intellij-avro-parquet-plugin#95]
After installing and enabling the extension in IntelliJ's settings, an error popup appears in the IntelliJ windows saying "IDE error occurred".
![image](https://user-images.githubusercontent.com/35801942/157907705-d0b1f483-51e4-49d3-b435-0ccce97961e0.png)

There are 2 stacktraces :
1/
```
com.intellij.diagnostic.PluginException: Cannot create class uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Avro and Parquet Viewer, id=uk.co.hadoopathome.intellij.avro.intellijavroviewer, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.3\plugins\intellij-avro-parquet-viewer-3.0.0.jar, version=3.0.0, package=null, isBundled=false), packagePrefix=null, instanceId=1, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:869)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:886)
	at com.intellij.openapi.wm.ToolWindowEP.getToolWindowFactory(ToolWindowEP.java:129)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$$special$$inlined$processDescriptors$1.accept(ToolWindowManagerImpl.kt:2351)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$$special$$inlined$processDescriptors$1.accept(ToolWindowManagerImpl.kt:86)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:299)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:144)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.<init>(ToolWindowManagerImpl.kt:2396)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.<init>(BackendServerToolWindowManager.kt:29)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateService(ComponentManagerImpl.kt:1044)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invoke(ComponentManagerImpl.kt:1016)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.run(ComponentManagerImpl.kt:56)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:845)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$2.run(ComponentManagerImpl.kt:1031)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:2984)
	at com.intellij.idea.StartupUtil.start(StartupUtil.java:297)
	at com.intellij.idea.Main.bootstrap(Main.java:134)
	at com.intellij.idea.Main.main(Main.java:82)
Caused by: java.lang.IllegalAccessException: no such constructor: uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow.<init>()void/newInvokeSpecial
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:959)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:830)
	... 34 more
Caused by: java.lang.NoClassDefFoundError: org/fife/ui/rtextarea/RTextScrollPane
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
	... 37 more
Caused by: java.lang.ClassNotFoundException: org.fife.ui.rtextarea.RTextScrollPane PluginClassLoader(plugin=PluginDescriptor(name=Avro and Parquet Viewer, id=uk.co.hadoopathome.intellij.avro.intellijavroviewer, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.3\plugins\intellij-avro-parquet-viewer-3.0.0.jar, version=3.0.0, package=null, isBundled=false), packagePrefix=null, instanceId=1, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 40 more
```
and 2/
```
com.intellij.diagnostic.PluginException: Cannot create class uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Avro and Parquet Viewer, id=uk.co.hadoopathome.intellij.avro.intellijavroviewer, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.3\plugins\intellij-avro-parquet-viewer-3.0.0.jar, version=3.0.0, package=null, isBundled=false), packagePrefix=null, instanceId=1, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:869)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:886)
	at com.intellij.openapi.wm.ToolWindowEP.getToolWindowFactory(ToolWindowEP.java:129)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.beanToTask(ToolWindowManagerImpl.kt:485)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$beanToTask(ToolWindowManagerImpl.kt:86)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$computeToolWindowBeans$$inlined$processDescriptors$1.accept(ToolWindowManagerImpl.kt:2354)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$computeToolWindowBeans$$inlined$processDescriptors$1.accept(ToolWindowManagerImpl.kt:86)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:299)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:144)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.computeToolWindowBeans(ToolWindowManagerImpl.kt:2351)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$computeToolWindowBeans(ToolWindowManagerImpl.kt:86)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$InitToolWindowsActivity.runActivity(ToolWindowManagerImpl.kt:2159)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:312)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:293)
	at com.intellij.ide.startup.impl.StartupManagerImpl.executeActivityFromExtensionPoint(StartupManagerImpl.kt:222)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$executeActivityFromExtensionPoint(StartupManagerImpl.kt:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$runActivity$lambda$1.accept(StartupManagerImpl.kt:172)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$runActivity$lambda$1.accept(StartupManagerImpl.kt:62)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processImplementations(ExtensionPointImpl.java:314)
	at com.intellij.ide.startup.impl.StartupManagerImpl.projectOpened(StartupManagerImpl.kt:171)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt.openProject(ProjectManagerExImpl.kt:496)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt.access$openProject(ProjectManagerExImpl.kt:1)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:143)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:58)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:94)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalAccessException: no such constructor: uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow.<init>()void/newInvokeSpecial
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:959)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:830)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: org/fife/ui/rtextarea/RTextScrollPane
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
	... 44 more
Caused by: java.lang.ClassNotFoundException: org.fife.ui.rtextarea.RTextScrollPane PluginClassLoader(plugin=PluginDescriptor(name=Avro and Parquet Viewer, id=uk.co.hadoopathome.intellij.avro.intellijavroviewer, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.3\plugins\intellij-avro-parquet-viewer-3.0.0.jar, version=3.0.0, package=null, isBundled=false), packagePrefix=null, instanceId=1, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 47 more
```

Plugin version used: 3.0.0
IntelliJ Community version : 2021.3.1
OS : Windows 10 Enterprise

**Comment by benwatson528** [comment]
![image](https://user-images.githubusercontent.com/6214761/158052458-1d7f569f-9bf6-429f-aed5-27ec4e8851ba.png)
I've just downloaded 2021.3.1 and was able to install the plugin. I can also see the missing class in the plugin zip so that looks ok:
![image](https://user-images.githubusercontent.com/6214761/158052548-0e3aab64-d42d-48ce-a30a-c9f1a6b5919f.png)

I don't have any great advice beyond

1. Un-install and re-install the plugin.
2. Upgrade IntelliJ to the latest version if possible.
